version: '2.1'
services:
  antd-testsys-client:
    image: 'nginx:alpine'
    container_name: 'studysys-client'
    ports:
      - '81:80'
    expose:
      - '80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - './build:/usr/share/nginx/html'
    # command: 'sh -c "npm config set registry https://registry.npm.taobao.org && /bin/sh"'