export const FETCH_CHARTSDATA = 'FETCH_CHARTSDATA';
export const FETCH_CHARTSDATA_SUCCESS = 'FETCH_CHARTSDATA_SUCCESS';
export const FETCH_CHARTSDATA_FAILED = 'FETCH_CHARTSDATA_FAILED';

export const FETCH_VOUCHINFO = 'FETCH_VOUCHINFO';
export const FETCH_VOUCHINFO_SUCCESS = 'FETCH_VOUCHINFO_SUCCESS';
export const FETCH_VOUCHINFO_FAILED = 'FETCH_VOUCHINFO_FAILED';

export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED';
export const USER_LOGOUT = 'USER_LOGOUT';

export const VALI_SIGNIN = 'VALI_SIGNIN';
export const VALI_USERNAME = 'VALI_USERNAME';
export const VALI_USERNAME_SUCCESS = 'VALI_USERNAME_SUCCESS';
export const VALI_USERNAME_FAILED = 'VALI_USERNAME_FAILED';
export const VALI_NICKNAME = 'VALI_NICKNAME';
export const VALI_NICKNAME_SUCCESS = 'VALI_NICKNAME_SUCCESS';
export const VALI_NICKNAME_FAILED = 'VALI_NICKNAME_FAILED';
export const VALI_EMAIL = 'VALI_EMAIL';
export const VALI_EMAIL_SUCCESS = 'VALI_EMAIL_SUCCESS';
export const VALI_EMAIL_FAILED = 'VALI_EMAIL_FAILED';
