export const FETCH_CHARTSDATA = 'FETCH_CHARTSDATA';
export const FETCH_CHARTSDATA_SUCCESS = 'FETCH_CHARTSDATA_SUCCESS';
export const FETCH_CHARTSDATA_FAILED = 'FETCH_CHARTSDATA_FAILED';

export const FETCH_VOUCHINFO = 'FETCH_VOUCHINFO';
export const FETCH_VOUCHINFO_SUCCESS = 'FETCH_VOUCHINFO_SUCCESS';
export const FETCH_VOUCHINFO_FAILED = 'FETCH_VOUCHINFO_FAILED';
